logo: # add logo name
title: EAH - Emigratie Adviesbureau Hiltemann
description: >
  EAH zorgt voor verantwoorde begeleiding van particulieren en bedrijven die een
  visum nodig hebben om te werken, studeren of permanent te wonen in Australië, Canada
  Nieuw-Zeeland of de Verenigde Staten. Ook voor overige landen bieden wij op-maat
  begeleiding.
permalink: '/:categories/:title/'
baseurl: ""
url: "https://www.emigratie-adviesbureau-hiltemann.com"
image: leaving.jpg

# Author settings
author-pic: paulhiltemann.jpg
author-name: Paul Hiltemann
about-author: Paul Hiltemann is een van de meest ervaren emigratie consulenten van Nederland. Hij heeft jarenlang gewerkt als immigratie specialist op de Canadese Ambassade in Den Haag en heeft daarna in 1997 Emigratie Adviesbureau Hiltemann (EAH) opgericht. Als consulent heeft hij altijd contact gehouden met de diverse federale en provinciale instanties die het immigratie beleid van Canada bepalen en uitvoeren. Ook is hij helemaal thuis bij het Australische Department of Immigration and Border Protection (DIBP) en heeft hij een speciale relatie met de staat Tasmania en het Australian Capital Territory.
email: paulhiltemann@ziggo.nl
phone: +31 644 657 859
website: https://emigratie-adviesbureau-hiltemann.com

# Tracker
analytics: UA-15037050-1

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
