logo: # add logo name
title: EAH - Emigratie Adviesbureau Hiltemann
description: > # this means to ignore newlines until "baseurl:"
  EAH zorgt voor verantwoorde begeleiding van particulieren en bedrijven die een
  visum nodig hebben om te werken, studeren of permanent te wonen in Australië, Canada
  Nieuw-Zeeland of de Verenigde Staten. Ook voor overige landen bieden wij op-maat
  begeleiding.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.emigratie-adviesbureau-hiltemann.com" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: # your name
about-author: # about author
email: paulhiltemann@ziggo.nl # your email
phone: +31 555 5555 # your pnone number
website: https://dwayne.example.com # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
